### ISSUE TITLE
Portability with Intel compiler

### ISSUE THREAD

**Issue by joseeroman** [eigs/EVSL#19]
I have tried building on OpenSuse 42.3 with icc 18 and found two issues. I am giving a fix for both of them, don't know if they are the best solution.

- `M_PI` is undefined in `ratfilter.c`, can be fixed by adding `#define _GNU_SOURCE` at the top of the file.
- `CLOCK_MONOTONIC` is undefined in `timing.c`, can be fixed by adding `#define _POSIX_C_SOURCE 199309L`  at the top of the file.

**Comment by liruipeng** [comment]
Hi @joseeroman , Can you please let me know if PR #22 can fix the issues? I don't have the platform you mentioned to test at hand. Thank you very much!

**Comment by joseeroman** [comment]
I no longer have access to that system. I have made a fresh installation of OpenSuse leap 15.3 with OneAPI 2021.4, and the errors do not appear. With PR #22 there are no errors either. So I am closing this issue. Thanks.
