### ISSUE TITLE
LanDos deprecation

### ISSUE THREAD

**Issue by AerysL** [eigs/EVSL#7]
I've finished setting up LanDosG such that it can now handle the standard eigenvalue problem in addition to the generalized eigenvalue problem (and updated the TESTS/Landos/LanDos.c test to show the new version). While it's signature/declaration/API is very similar to the old LanDos function (which I see is used LaPLanN test), it is not identical. Furthermore the output is not identical.

One run of the output is as follows, where the G function is the function which handles both standard and general problems, and the S function is the old which only handles standard.
![tester](https://user-images.githubusercontent.com/16215401/27142471-c01e20a4-50f0-11e7-97c2-1e5ff1015505.png)

 I can think of three approaches of how to handle this:

1.  (What I've done already) Leave a note in the LanDos (standard) documentation indicating it has been deprecated, and add a print statement stating so to the program, but leave it's implementation the same.

2.  Change the implementation of the LanDos function to simply act as a wrapper to the LanDosG function. Would preserve current LanDos calls, but would impact the output.

3. Do nothing. This however leaves two ways to do the standard problem for landos (LanDos, and LanDosG), fragmenting the code but preserves API.

Thoughts?
Note: The changes I have described have not yet been merged into eigs/EVSL, but exist on my fork in AerysL/EVSL.

**Comment by eigs** [comment]
Not sure it is worth having one code to handle both generalized and standard problems. You can just update the old LanDos function and add a mention that LanDosG does both generalized and standard problems. People wanting to test this for a standard problem would prefer simplicity and use LanDos..

YS

**Comment by eigs** [comment]
One more thing: It is normal to have different results for each run.. the algorithms use random vectors and these are different each time.
